dist: xenial
language: python
sudo: false

services:
  - docker

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libffi-dev
      - libssl-dev
      - swig

install:
  - pip install pre-commit
  - pip install -e .

script:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]] || [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]
    then
      pre-commit run --all-files
    fi
  - python setup.py test
  - python setup.py sdist

after_success:
  - mkdir deploy
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]
    then
      cp dist/fido2-*.tar.gz deploy/python-fido2-$TRAVIS_BRANCH.tar.gz
      docker build -t xenial -f docker/xenial/Dockerfile .
      id=$(docker create xenial)
      docker cp $id:/python-fido2-debian-packages.tar.gz deploy/python-fido2-$TRAVIS_BRANCH-deb.tar.gz
    fi

deploy:
  provider: s3
  access_key_id: "$AWS_KEY_ID"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$AWS_BUCKET"
  skip_cleanup: true
  acl: public-read
  region: eu-west-1
  local-dir: "deploy/"
  upload-dir: "python-fido2"
  on:
    all_branches: true
