language: python
sudo: false

services:
  - docker

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5-5.7.1-beta"

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libffi-dev
      - libssl-dev
      - swig

install:
  - pip install pre-commit
  - pip install -e .

script:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" != "pypy3.5-5.7.1-beta" ]]
    then
      pre-commit run --all-files
    fi
  - python setup.py test

after_success:
  - mkdir deploy
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]
    then
      docker build -t xenial -f docker/xenial/Dockerfile .
      id=$(docker create xenial)
      docker cp $id:/python-fido-host-debian-packages.tar.gz deploy/python-fido-host-$TRAVIS_BRANCH-deb.tar.gz
    fi

deploy:
  provider: s3
  access_key_id: "$AWS_KEY_ID"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$AWS_BUCKET"
  skip_cleanup: true
  acl: public-read
  region: eu-west-1
  local-dir: "deploy/"
  upload-dir: "python-fido-host"
  on:
    all_branches: true
